// Game definitions and question banks for Nite — extracted to a separate file to keep index.html lighter.
const GAMES={
  '21q':    {icon:'🤔',name:'21 Questions',   desc:'Think of something — others ask yes/no questions to guess it'},
  'wyr':    {icon:'🤷',name:'Would You Rather',desc:'Choose between two options — then reveal what everyone picked'},
  'tot':    {icon:'🍕',name:'This or That',    desc:'Quick-fire picks between two things — see who matches!'},
  'nihe':   {icon:'🙅',name:'Never Have I Ever',desc:'Confess (or not) — see how you and your friends compare'},
  'confess': {icon:'🤫',name:'Confess',        desc:'Fun confessions — admit it or deny it, then reveal!'},
  'trivia': {icon:'🧠',name:'Trivia',           desc:'Answer questions from the web — challenge your room!'},
  'hottakes':{icon:'🌶️',name:'Hot Takes',      desc:'Agree or disagree on spicy opinion statements'},
  'ttt':    {icon:'⭕',name:'Tic Tac Toe',      desc:'Classic 3-in-a-row — be first to line up X or O!'},
  'c4':     {icon:'<svg viewBox="0 0 44 38" width="40" height="34" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="6" width="44" height="32" rx="4" fill="#1d4ed8"/><circle cx="8" cy="15" r="5.5" fill="#ef4444"/><circle cx="22" cy="15" r="5.5" fill="#facc15"/><circle cx="36" cy="15" r="5.5" fill="rgba(255,255,255,0.18)"/><circle cx="8" cy="29" r="5.5" fill="rgba(255,255,255,0.18)"/><circle cx="22" cy="29" r="5.5" fill="#ef4444"/><circle cx="36" cy="29" r="5.5" fill="#facc15"/><circle cx="3" cy="3" r="2.5" fill="#facc15"/><circle cx="13" cy="3" r="2.5" fill="#ef4444"/></svg>',name:'Connect Four',     desc:'Drop pieces to build 4-in-a-row before your opponent'},
  'chk':    {icon:'<svg viewBox="0 0 40 40" width="38" height="38" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="4" fill="#78350f"/><rect x="0" y="0" width="10" height="10" fill="#fef3c7"/><rect x="20" y="0" width="10" height="10" fill="#fef3c7"/><rect x="10" y="10" width="10" height="10" fill="#fef3c7"/><rect x="30" y="10" width="10" height="10" fill="#fef3c7"/><rect x="0" y="20" width="10" height="10" fill="#fef3c7"/><rect x="20" y="20" width="10" height="10" fill="#fef3c7"/><rect x="10" y="30" width="10" height="10" fill="#fef3c7"/><rect x="30" y="30" width="10" height="10" fill="#fef3c7"/><circle cx="5" cy="15" r="3.5" fill="#dc2626"/><circle cx="25" cy="5" r="3.5" fill="#dc2626"/><circle cx="35" cy="15" r="3.5" fill="#1e293b"/><circle cx="15" cy="5" r="3.5" fill="#1e293b"/></svg>',name:'Checkers',          desc:"Jump your opponent's pieces across the board to win"},
  'chess':  {icon:'♟️',name:'Chess',            desc:'The ultimate strategy game — checkmate the king to win'},
};

// ═══ QUESTION BANKS ════════════════════════════
const WYR_BANK=[
  ["fly anywhere for free","have unlimited food forever"],["always be 10 min late","always be 20 min early"],
  ["only be able to whisper","only be able to shout"],["be incredibly funny","be incredibly smart"],
  ["live without music","live without TV/shows"],["always know when someone is lying","always get away with lying"],
  ["never use social media again","never watch another show"],["be able to teleport","be able to time travel"],
  ["have a pause button for your life","have a rewind button for your life"],["always feel too hot","always feel too cold"],
  ["live in a world with no internet","live in a world with no cars"],["have free Starbucks for life","have free Amazon Prime for life"],
  ["talk to animals","speak every language"],["be famous after you die","be famous now but forgotten later"],
  ["never have to sleep","never have to eat"],["have no elbows","have no knees"],
  ["be the funniest person in the room","be the smartest person in the room"],["always have wet socks","always have sand in your shoes"],
  ["give up your phone for a month","give up your computer for a month"],["live on a houseboat","live in a treehouse"],
  ["know how you'll die","know when you'll die"],["eat your favorite food every day","never eat it again"],
  ["have the ability to read minds","be invisible at will"],["win $100 now","get $10 a day forever"],
  ["be able to control fire","be able to control water"],["live in extreme cold","live in extreme heat"],
  ["never be able to run","never be able to walk slowly"],["be able to see 10 min into the future","see 10 years into the future"],
  ["always have hiccups","always have a runny nose"],["travel the world alone","stay home with best friends"],
  ["only eat sweet food","only eat savory food"],["have a photographic memory","be able to forget anything you want"],
  ["be incredibly tall","be incredibly short"],["be a superhero with a lame power","be a villain with an awesome power"],
  ["always have the best parking spot","always have a front row seat everywhere"],["find true love","find $10M"],
  ["be an amazing singer","be an amazing athlete"],["be stuck 5 years in the past","5 years in the future"],
  ["never age physically","never age mentally"],["have a pet dragon","have a pet dinosaur"],
  ["know all the secrets of the universe","be the richest person ever"],["always speak your mind","never be able to share your opinion"],
  ["have no taste","have no smell"],["be the best at everything you try","be average at everything"],
  ["sleep 12 hrs a night","survive on 4 hrs"],["never have to clean","never have to cook"],
  ["be extremely lucky","be extremely skilled"],["have everyone like you","have only a few deep friendships"],
  ["lose all your photos","lose all your contacts"],["only watch one TV show forever","only listen to one album forever"],
  ["be the hero of a story","be the best friend/sidekick"],["always be overdressed","always be underdressed"],
  ["never be able to lie","never be able to tell the truth"],["go to space","go to the bottom of the ocean"],
  ["have a talking dog","have a talking cat"],["never worry about money","never worry about health"],
  ["be able to fly but very slowly","teleport but only 5 feet at a time"],["have perfect hair every day","have perfect skin every day"],
  ["know all the world's languages","know how to play every instrument"],["have Wi-Fi everywhere","have free coffee everywhere"],
  ["be ridiculously over-qualified for every job","be slightly unqualified for your dream job"],
  ["live in the city","live in the country"],["never feel pain","never feel fear"],
  ["be able to breathe underwater","survive without breathing for an hour"],
  ["have a reusable bag of snacks that never empties","have unlimited pizza delivery forever"],
  ["fight one horse-sized duck","fight 100 duck-sized horses"],["be an Olympic athlete","be a Nobel Prize winner"],
  ["have every day be a Friday","have every day be your birthday"],["age only from the neck up","age only from the neck down"],
  ["be Spider-Man","be Batman"],["always have fast Wi-Fi","always have a full phone battery"],
  ["forget who everyone is for a day","have everyone forget who you are for a day"],
  ["bungee jump","skydive"],["meet your past self","meet your future self"],
  ["be a master chef","be a master builder"],["have a library of every book ever","have a collection of every show ever"],
  ["wake up with a different face","wake up with a different voice every day"],
  ["never be able to use GPS","never be able to use Google"],
  ["always smell something burning","always hear faint music no one else can hear"],
  ["your emails are all public","your searches are all public"],
  ["only be able to eat cold food","only be able to drink warm drinks"],
  ["skip a decade of your life","live a decade of your life twice"],
  ["be the oldest sibling","be the youngest sibling"],
  ["have every day be a weekend","have every weekend be a week long"],
  ["write a bestselling novel","direct an award-winning film"],
  ["have unlimited coffee","have unlimited energy drinks"],
  ["be a famous scientist","be a famous artist"],["swap lives with your best friend","swap lives with a celebrity"],
  ["only travel by plane","only travel by boat"],["have free healthcare","have free education"],
  ["never stub your toe again","never get a brain freeze again"],
  ["be a morning person","be a night owl"],["be incredibly beautiful","be incredibly kind"],
  ["relive your best memory","skip your worst memory"],
  ["be the first person on Mars","be the last person on Earth"],
  ["know the exact date of your death","not know but live 20 years longer"],
  ["have a robot assistant","have a human assistant"],["surf perfect waves","ski perfect powder always"],
  ["have the ability to stop time","age at half speed"],["always get free upgrades","always get priority service"],
  ["own a mansion with roommates","own a small house alone"],["get paid to eat","get paid to sleep"],
];

const NIHE_BANK=[
  "gone skydiving","stayed up all night with friends","eaten an entire pizza by myself",
  "sung karaoke in public","lied about watching a show to fit in","cried at a show",
  "fallen asleep in class or a meeting","sent a text to the wrong person","ghosted someone",
  "stayed in a relationship too long","eaten food off the floor","been to a music festival",
  "pretended to like a gift I hated","gone skinny dipping","broken a bone",
  "been on a road trip longer than 8 hours","laughed so hard I cried","pulled an all-nighter",
  "eaten fast food 3+ days in a row","had a crush on a friend's partner","been in a car accident",
  "cheated on a test","lied about my age","worn the same outfit two days in a row",
  "eaten food that wasn't mine in the fridge","been to another country","met someone from the internet in person",
  "been to a casino","gotten lost in a foreign city","pretended to be sick to skip something",
  "danced in the rain","gone to a midnight premiere event","watched the sunrise after a full night out",
  "made a huge impulse purchase I regretted","unfollowed someone on every platform after a breakup",
  "stayed in a hotel alone","been on TV or in a newspaper","run a 5K or longer",
  "eaten food from a vending machine as a meal","convinced someone of something completely false",
  "forgotten a close friend's birthday","had a phase I'm now embarrassed by",
  "been told I'm a bad driver","laughed at the worst possible moment",
  "been blackout clumsy and knocked something over in a store","gone vegetarian or vegan for a period of time",
  "posted something I immediately regretted","gotten a speeding ticket","been to a theme park 3+ times",
  "made a bet and lost","danced alone in my room with full commitment","cried because I was too tired",
  "googled myself","re-read a text 20 times before sending","fallen for a scam",
  "spent more than $100 on a single meal","stolen something as a kid",
  "had a dream about someone in this room","said something mean I regret",
  "binge-watched an entire season in one day","given a fake number to someone",
  "pretended to be on the phone to avoid someone","been nervous to the point of shaking",
  "run away from something that turned out harmless","moved to a different city","tried a new extreme sport",
  "stayed up reading a book all night","done something dangerous for a dare",
  "accidentally liked a very old photo while stalking someone's profile",
  "broken someone's trust","been on a blind date","planned something elaborate and had it fail",
  "regretted a haircut","lost something irreplaceable","had an imaginary friend as a kid",
  "talked to a stranger on a plane for hours","eaten something exotic like insects",
  "made a huge mess and left it for someone else","deleted all my social media for a while",
  "gotten matching items with a friend or partner","been star-struck meeting someone famous",
  "pulled an epic prank","been terrified of something embarrassing","saved someone from something",
  "lied to get into somewhere","stayed friends with an ex","spent money I didn't have",
  "changed my opinion on something I felt strongly about","been voted most likely to something",
  "kept a journal for more than a year","lost a friend over a misunderstanding",
  "been to a protest or march","adopted a pet on impulse","screamed into a pillow",
  "watched a film or show in a language I don't speak without subtitles","laughed until I snorted",
  "eaten an entire bag of chips in one sitting","completely failed at something I bragged about",
  "introduced myself with the wrong name by accident","had a recurring nightmare",
  "made something with my hands I was truly proud of","given an anonymous compliment to a stranger",
  "used a shopping cart as a scooter in an empty parking lot","called a teacher Mom or Dad by accident",
  "been the last one picked for a team","given a standing ovation at a show",
  "learned a party trick","gone a full week without checking social media",
  "eaten the last slice without asking","crashed a party or event",
  "had a phase where I was obsessed with a very niche hobby","cried happy tears",
  "been on a helicopter or small plane","bet on a sports game","re-gifted a gift",
  "accidentally walked into the wrong bathroom","been on a game show or trivia night and won",
];

const TOT_BANK=[
  ["pizza","tacos"],["sweet","salty"],["coffee","tea"],["beach vacation","mountain vacation"],
  ["morning person","night owl"],["texting","calling"],["dogs","cats"],["summer","winter"],
  ["movies at home","movies at the theater"],["books","podcasts"],["city life","country life"],
  ["window seat","aisle seat"],["cooking","ordering out"],["early bird flight","red-eye flight"],
  ["camping","hotel"],["driving","flying"],["board games","video games"],["burgers","sushi"],
  ["horror movies","comedies"],["big parties","small hangouts"],["planning ahead","winging it"],
  ["chocolate","vanilla"],["hiking","swimming"],["being famous","being rich"],
  ["long showers","long baths"],["road trip","cruise"],["spicy food","mild food"],
  ["reading the book first","watching the movie first"],["sunrise","sunset"],
  ["staying in","going out"],["gaming console","PC gaming"],["Android","iPhone"],
];

const CONFESS_BANK=[
  "stalked an ex on social media this week","talked to myself out loud today",
  "pretended to know a song I'd never heard","laughed at my own joke before anyone else",
  "rehearsed a text before sending it","googled something embarrassing recently",
  "have a playlist I'd never show anyone","practiced a conversation in the mirror",
  "screenshotted a text to show a friend","have a secret guilty pleasure show",
  "cried during a commercial","forgot someone's name mid-introduction",
  "have never seen a movie everyone says is a classic","judged someone by their profile picture",
  "eaten something after the expiration date and didn't tell anyone","re-watched my own story to see who viewed it",
  "have a nickname for a friend they don't know about","pretended to be busy to avoid plans",
  "have a hidden talent no one knows about","laughed at something inappropriate at the worst time",
];

const HOTTAKES_BANK=[
  "Pineapple on pizza is actually good","The last season of a show is almost always the worst",
  "Sleep is more important than a social life","Texting is better than calling",
  "Dogs are better than cats","Mornings are better than nights",
  "Working from home is better than going to an office","Social media does more harm than good",
  "Reality TV is actually entertaining","Spicy food is overrated",
  "Summer is the best season","Breakfast is the most overrated meal",
  "Introverts have more fun","Paying for a gym is wasteful if you don't go",
  "Sequels are almost always worse than the original","Personality matters more than looks",
  "Money can buy happiness","Hard work beats natural talent",
  "True crime content glorifies criminals","Astrology is a valid way to understand people",
  "Long-distance relationships can work","People who wake up early are happier",
  "Video games are a legitimate art form","Flying is less stressful than driving",
  "Renting is smarter than owning a home","Dessert should come before dinner",
  "Silence is better than small talk","Streaming has changed the theater experience forever",
  "Naps are a superpower","Online friends can be as real as in-person friends",
  "Crocs are actually comfortable and that matters more than style",
  "Remakes should always be judged on their own merit","Gifting cash is thoughtful, not lazy",
];

